import { useNavigate } from 'react-router-dom'
import './Tutorial.css'
import { Services, Edit, Pan } from 'grommet-icons'
import customNode from '../../../src/assets/CustomNode.png'
import generatedNode from '../../../src/assets/AutoGeneratedNode.png'

const Tutorial = () => {

  const navigate = useNavigate()

  return (
    <div className='about__tutorial'>
        <div className='about__tutorial--left-view'>
            <div className='tutorial'>
                <p className='intro'>Though not explicitly specified, CoursesFlow have 2 modes that you can choose: custom and auto-generated, each 
                associates with its own type of nodes.</p>
                <p className='mode'>Auto-generated Mode <Services /></p>
                <ul>
                  <li>Currently, this mode only applies to students majoring in Computer Science at Michigan State University</li>
                  <li>Just type in the course code, then choose Generate Flow button. A chronological flow of courses will be shown right away!.
                    You can freely move the nodes around whatever you want for better look 🤩
                  </li>
                  <li>
                  You can then create an account or log in to your old account to freely save your work to the server and edit it later.
                  </li>
                </ul>
                <p className='mode'>Custom Mode <Edit /></p>
                <p className='intro'>There will be a starting node in this mode. The node associated with this node is special:</p>
                <ul>
                  <li>To move it around, hold the <Pan size='small'/> icon</li>
                  <li>To change content of node, type in the center.</li>
                  <li>To create new node, drag from the current node to the plane. A new node will be auto-created for you.</li>
                </ul>   
              Now we are ready, let's get started! <button className='btn' onClick={() => navigate('/main')}>Go to feature</button>        
            </div>
            {/* This is for nodes illustrations */}
            <div className='nodes-illustration'>
              <div>
                <img src={generatedNode} alt='pic of auto generated node' className='nodes-img'/>         
                <p className='img-note'>Nodes from auto-generated mode</p> 
              </div>

              <div>
                <img src={customNode} alt='pic of custom node' className='nodes-img'/>
                <p className='img-note'>Nodes from custom mode</p>
              </div>
            </div>
        </div>
        <div className='about__tutorial--right-view'>
          <h1>How to use</h1>
        </div>
    </div>
  )
}

export default Tutorial